### ISSUE TITLE
Compilation failed: "unhandled &1 outside of a capture"

### ISSUE THREAD

**Issue by cyranix** [azukiapp/elixir-protobuf#2]
```
** (CompileError) deps/protobuf/lib/protobuf.ex:29: unhandled &1 outside of a capture
    src/elixir_translator.erl:573: :elixir_translator.translate_arg/2
    lists.erl:1339: :lists.mapfoldl/3
    src/elixir_translator.erl:580: :elixir_translator.translate_args/2
    src/elixir_translator.erl:549: :elixir_translator.translate_local/4
    src/elixir_translator.erl:573: :elixir_translator.translate_arg/2
    lists.erl:1339: :lists.mapfoldl/3
    lists.erl:1340: :lists.mapfoldl/3
```

attempted under Elixir 0.10.4-dev

**Comment by cyranix** [comment]
The problem itself is fixed, but I still encounter the behavior when trying to use azukiapp/elixir-rethinkdb as a dependency in my project. Does a new version need to be tagged and referenced in the other project's mixfile? I'm fairly new to all of this, so I don't really know how things are supposed to behave in Mix.

**Comment by nuxlli** [comment]
You need to upgrade the mixfile, but do not worry, I'm working on it right now. Including updating the box to the elixir wercker 0.10.3 :D

Now a tip: you could force a new version of `elixir-protobuf` in your project:

``` elixir
{ :protobuf, github: "azukiapp/elixir-protobuf", tag: "v0.0.3", override: true },
```

**Comment by cyranix** [comment]
Ah, very good to know, even if you are on top of things. Thanks!

**Comment by nuxlli** [comment]
@cyranix done: https://github.com/azukiapp/elixir-rethinkdb/tree/v0.2.3
